### ISSUE TITLE
Textfields/Captions

### ISSUE THREAD

**Issue by kleeaar** [kit-ipe/bora#10]
Hey Nicholas
We need/would like to have some extra headings to group different types of sensors in the display. 
Is there a possibility to add headings to the list, just like sensors?
i.e. giving a heading-id (instad of a KATRIN Number) to the add-sensor-page and then just use the title-output?

![heading](https://cloud.githubusercontent.com/assets/19652477/15703355/115537ea-27e5-11e6-9e2d-4b05a234945f.png)

**Comment by nicolaisi** [comment]
I thought about this before, this should be included.

**Comment by kleeaar** [comment]
Ah, ok.
But what do I need as input for the adei2rest.py or as path for the add page, respectively?
Didn't get that :D
or what is the procedure to get a heading only in the designer?

**Comment by nicolaisi** [comment]
This is still missing, currently you cannot add only header text to the page. Because I bind everything with data entry. Hopefully tonight I can add this feature. 

So for now, you cannot add only header.

**Comment by kleeaar** [comment]
ah, i thought you ment that it was already included...
No hurry ;-)

**Comment by nicolaisi** [comment]
I added this.

Usage:
<img width="859" alt="screen shot 2016-06-29 at 14 53 01" src="https://cloud.githubusercontent.com/assets/2225781/16452582/7ce54772-3e09-11e6-9da5-16b9b49f1186.png">
