### ISSUE TITLE
Formulas

### ISSUE THREAD

**Issue by kleeaar** [kit-ipe/bora#11]
one more thing with lower priority:
We need the possibility to add a formula, which will calculate the correct value, from the adei output. (e.g. neccessary to calculate the magnetic field, since we only have a current given in adei.)
It needs only to parse simple expressions with +, -, * , /
Hope thats not too much work :)

**Comment by nicolaisi** [comment]
Seems like there's a few libraries that supports this feature:
https://silentmatt.com/javascript-expression-evaluator/
http://mathjs.org/

I'll implement this when I'm back from Africa.

**Comment by nicolaisi** [comment]
80dc056a5f8bbc70f4957feddb879e0e0733b1f3
