### ISSUE TITLE
time of last sync

### ISSUE THREAD

**Issue by kleeaar** [kit-ipe/bora#14]
Maybe it would be better to write _time of last sync_ as a value to the cache.yaml and show this value on the website.
Then one can see clearly that the cache was built properly or if not, when it was done the last time.

**Comment by nicolaisi** [comment]
Agree, should we show the last time sync in the tooltip?

**Comment by kleeaar** [comment]
We’re not sure if we need to show additional information on the sensors. #15 
It was just the idea to show  the last time on the left top corner when the cache.yaml was updated instead of the time when the status display read the cache.  This could also contain some alert, if the cache.yaml is outdated.

**Comment by nicolaisi** [comment]
be21fd02f33669ccb6362b156f90822f51f793d1

If the cache is not running, the time will be static.

**Comment by kleeaar** [comment]
Yes, maybe it would be good to receive a mail if the status monitor is not updating anymore. 
But that can be implemented afterthe basic funtions are implemented.
Currently its working stable, so thats all fine.
