### ISSUE TITLE
Decimal number not working in status page [Bug] 

### ISSUE THREAD

**Issue by chinyihan** [kit-ipe/bora#160]
![Screenshot 2024-06-24 124407](https://github.com/kit-ipe/bora/assets/127185216/a96845dc-47b4-41bf-b440-cf10498b8376)
![Screenshot 2024-06-24 124424](https://github.com/kit-ipe/bora/assets/127185216/69d84cd3-7f7d-4185-88a8-52a1f2edaa31)

**Comment by nicolaisi** [comment]
5c18d3fa2e7ef62c292ae1e8ec7624e81e4a9242
