### ISSUE TITLE
ventil missing

### ISSUE THREAD

**Issue by nicolaisi** [kit-ipe/bora#2]
Designer page should add the ventil option.

**Comment by kleeaar** [comment]
Hey Nicholas
I think there is a similar problem with the operational modes.
Since this adei-entry is only returning integers, one needs to add the text that is shown manually.
Maybe it would be the easiest way, if there is an option in the newly added select-field for integer-to-string-conversion and one can submit an array with ; as delimiters in the units-inputfield ?

Grüße
Lutz

**Comment by nicolaisi** [comment]
Hi Lutz,

what are the possible outcome for the operational modes? I can't find this in the excel sheet, or did I missed it? You're idea is good, I might proceed as you suggested, but firstly I need to know which Katrin number is this.

Rgds,
Nicholas

**Comment by kleeaar** [comment]
its the section _CPS Mode of Operation:_ right at the bottom with the KATRIN number 320-MOD-0-0001

**Comment by nicolaisi** [comment]
Usage:

<img width="772" alt="screen shot 2016-05-31 at 11 32 59" src="https://cloud.githubusercontent.com/assets/2225781/15670115/ff52fe0e-2723-11e6-8063-3ce6897f96a9.png">


<img width="753" alt="screen shot 2016-05-31 at 11 34 44" src="https://cloud.githubusercontent.com/assets/2225781/15670117/020e7c68-2724-11e6-8a2e-d9b308d9614b.png">

**Comment by nicolaisi** [comment]
Need to use dictionary format in the value.

**Comment by kleeaar** [comment]
Great!
It seems to work properly except one thing:
We just tested a valve (311-RBY-1-5051) and it appeared grey in the status display. Actually we wanted it to be green if it’s open and red if it’s closed. (The grey color was just for the valves that arent included to adei yet. Sorry for the misconception)
Could you add this feature?

**Comment by nicolaisi** [comment]
Ahh, yes. I can do this.

**Comment by nicolaisi** [comment]
I added the red and green ventil. But currently there's no value returned, in this case I use grey. Is it ok?

If you look at the ADEI graph, there were no incoming data for this attribute.  I used the "window=-1" parameter, which implies I'm calling the last recent value. Since there's no value, I'm getting empty value.

<img width="1154" alt="screen shot 2016-05-31 at 21 04 08" src="https://cloud.githubusercontent.com/assets/2225781/15687402/c44c064c-2774-11e6-8327-914fecea5875.png">

So now I set, on = green, off = red, no value = grey. Ok?

**Comment by kleeaar** [comment]
ah, youre right, this sensor has no entry since 13th May. 
Dont know why...
But the way you did it, is absolutely perfect! :)

**Comment by kleeaar** [comment]
one more thing with low priority:
could you add a coloring function for the integer-to-string function?
we also use that for the PS and DS magnets which are returning bools/integers and we transform the values to on/off. So we need the same option to give a value in the _condition red_ input for bools to be red (and stay black as default if none given)

**Comment by nicolaisi** [comment]
I'd added the colouring function to "integer-to-string" data type.

You just have to provide a colour hex code.

<img width="792" alt="screen shot 2016-06-29 at 13 27 36" src="https://cloud.githubusercontent.com/assets/2225781/16450478/7576406a-3dfd-11e6-9ed1-01af6c2e33a5.png">


I'll mark this as closed.

**Comment by kleeaar** [comment]
I used this for the PS Magnet (411-REI-1-1110-0030) on the right side, but the sensor value is still black.
Not sure if that function is yet available on our version of the monitor or it's a small bug.
#10 is working properly!

**Comment by nicolaisi** [comment]
Yup, it was a bug. The attribute checking was not correct. It's now fixed and working fine.
ebb60460bcbff5774a2501764f3fceb91b9b15af
