### ISSUE TITLE
small numbers to scientific

### ISSUE THREAD

**Issue by kleeaar** [kit-ipe/bora#23]
Hey Nicholas
We just found a new little problem:
we added the isolation vacuum on the right bottom. The values for the vacuum are commonly shown in scientific notation e.g. 5.2e-6 mbar. Because of the toFixed(2) formatting there is only shown 0.00 mbar.
The conversion to scientific notation can be done with `math.format(x,   {notation: 'exponential'});`
Would it be possible to add a checkbox for scientific notation to the designer interface.
That would be great!

**Comment by nicolaisi** [comment]
152046a4e4d1276341c67e8242cd93855097de87

**Comment by kleeaar** [comment]
Perfect :)
