### ISSUE TITLE
Link to ADEI

### ISSUE THREAD

**Issue by nicolaisi** [kit-ipe/bora#3]
All the data attributes should have a link to ADEI to monitor the data profiles.

**Comment by kleeaar** [comment]
Could you please also add the KATRIN number as title-attribute to the outgoing links. That would be great :)

**Comment by nicolaisi** [comment]
Upon hover, title appeared. Upon click, ADEI page will be shown.

<img width="506" alt="screen shot 2016-05-31 at 14 39 30" src="https://cloud.githubusercontent.com/assets/2225781/15674543/a39c4a1a-273d-11e6-8e2b-67d8eded951c.png">
